### ISSUE TITLE
NameErrorNameError: name 'post' is not defined

### ISSUE THREAD

**Issue by caiyingchun** [degiacom/JabberDock#2]
Hi,
I meet another issue below:
```
>> saving swarm state at repetition 3, step 300...
>> optimization time (sec): 70433.701

> POSTPROCESSING...
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/applic/POW_v2/POW.py", line 185, in <module>
  File "/home/applic/POW_v2/POW.py", line 185, in <module>
        post=comm.bcast( post,root=0)
post=comm.bcast( post,root=0)
NameErrorNameError: name 'post' is not defined
: name 'post' is not defined
Traceback (most recent call last):
  File "/home/applic/POW_v2/POW.py", line 185, in <module>
    post=comm.bcast( post,root=0)
  File "mpi4py/MPI/Comm.pyx", line 1257, in mpi4py.MPI.Comm.bcast
  File "mpi4py/MPI/msgpickle.pxi", line 628, in mpi4py.MPI.PyMPI_bcast
  File "mpi4py/MPI/msgpickle.pxi", line 104, in mpi4py.MPI.Pickle.dump
  File "mpi4py/MPI/msgpickle.pxi", line 93, in mpi4py.MPI.Pickle.cdumps
  File "/home/applic/miniconda2/lib/python2.7/site-packages/dill/_dill.py", line 265, in dumps
Traceback (most recent call last):
  File "/home/applic/POW_v2/POW.py", line 185, in <module>
    post=comm.bcast( post,root=0)
NameError: name 'post' is not defined
    dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
  File "/home/applic/miniconda2/lib/python2.7/site-packages/dill/_dill.py", line 259, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/applic/miniconda2/lib/python2.7/site-packages/dill/_dill.py", line 445, in dump
Traceback (most recent call last):
  File "/home/applic/POW_v2/POW.py", line 185, in <module>
    post=comm.bcast( post,root=0)
Traceback (most recent call last):
  File "/home/applic/POW_v2/POW.py", line 185, in <module>
    post=comm.bcast( post,root=0)
    StockPickler.dump(self, obj)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 224, in dump
NameError: name 'post' is not defined
Traceback (most recent call last):
  File "/home/applic/POW_v2/POW.py", line 185, in <module>
    post=comm.bcast( post,root=0)
NameError: name 'post' is not defined
    self.save(obj)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 731, in save_inst
    save(stuff)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/applic/miniconda2/lib/python2.7/site-packages/dill/_dill.py", line 912, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 731, in save_inst
    save(stuff)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/applic/miniconda2/lib/python2.7/site-packages/dill/_dill.py", line 912, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 396, in save_reduce
    save(cls)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/applic/miniconda2/lib/python2.7/site-packages/dill/_dill.py", line 1356, in save_type
Traceback (most recent call last):
  File "/home/applic/POW_v2/POW.py", line 185, in <module>
    post=comm.bcast( post,root=0)
NameError: name 'post' is not defined
    StockPickler.save_global(pickler, obj)
  File "/home/applic/miniconda2/lib/python2.7/pickle.py", line 754, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <class 'jabber.Jabber'>: it's not found as jabber.Jabber
NameError: name 'post' is not defined
```

I don't know why?
Thanks.

**Comment by dclw29** [comment]
Hi,
This is the same issue before, except now it's cropping up in the postprocessing step. My apologies I didn't apply the fix correctly to the entire optimiser.

To resolve this, please pull the latest version of JabberDock from github.

The good news it that you won't need to rerun the entire docking algorithm as before, the state should already be saved. So, let's say before you had a folder called `jd_tutorial/` in your home folder where you were performing your docking from. Whereas before you might have been typing in `jd_tutorial/`:

`dock.py -ir 1dfj_0_sim_map -il 1dfj_1_sim_map -np 12`
Now, from the same folder, can you instead type:
`mpirun -np 12 /folder/to/POW/POW_v2/parse.py input_ensemble`

where `/folder/to/POW/` is the path to where the updated POW_v2 has been installed (e.g. `/data/home/`).

This will skip the optimisation steps you've already performed before entirely, and go straight to the postprocessing (i.e. producing your models and clustering) and should only take a matter of minutes.
Note this is a fix for what you've currently achieved, in future everything should work from just the dock.py command, though you're always welcome to do the postprocessing step independently if you like.

Hope this helps. Let me know how it goes
Cheers,
Lucas

**Comment by caiyingchun** [comment]
cai yingchun 已与你共享 OneDrive 文件。若要查看，请单击下面的链接。
<https://1drv.ms/u/s!AsAj-3DL8oabiHNEOTiayCUwgIzR>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://1drv.ms/u/s!AsAj-3DL8oabiHNEOTiayCUwgIzR>
test_jd.zip<https://1drv.ms/u/s!AsAj-3DL8oabiHNEOTiayCUwgIzR>

Hi,
I do as what you told me, it works. But another issue raise.


>        Parallel Optimization Workbench (POW)            <
> (c) 2012-14, Laboratory for Biomolecular Modeling, EPFL <
>                                                         <
>                 -postprocess results -                  <

>> loading module generate_ensembly...
>> loading optimizer PSO...
>> parsing input file...
/home/applic/POW_v2/Default.py:117: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.high_input!="NA" and np.any(self.low_input>self.high_input):
>> importing data...

> Input DATA:
>> protein receptor: VHL_sim_map.pdb
>> ligand: BRD4_sim_map.pdb
>> importing PDB files...
>> importing density files...
>> postprocessing logfile pow_log.dat
>> 11818 solutions filtered
>> selecting 300 representatives with kmeans...
>> calculating pairwise RMSD of selected samples...
Traceback (most recent call last):
  File "/home/applic/POW_v2/parse.py", line 131, in <module>
    post.run()
  File "/home/applic/JabberDock/auto_scripts/generate_ensembly.py", line 314, in run
    R = jd.geometry.rotate_map(Ptest, COM = self.COM, R = R_pdb)
  File "geometry.pyx", line 146, in geometry.rotate_map
  File "geometry.pyx", line 192, in geometry.rotate_map
AttributeError: 'NoneType' object has no attribute 'properties'

I don't know whether it is related to the input file. I also mailed you my zip files.

Thanks.
________________________________
发件人: dclw29 <notifications@github.com>
发送时间: 2020年5月22日 10:02
收件人: degiacom/JabberDock <JabberDock@noreply.github.com>
抄送: Yingchun Cai <cai_yingchun@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [degiacom/JabberDock] NameErrorNameError: name 'post' is not defined (#2)


Hi,
This is the same issue before, except now it's cropping up in the postprocessing step. My apologies I didn't apply the fix correctly to the entire optimiser.

To resolve this, please pull the latest version of JabberDock from github.

The good news it that you won't need to rerun the entire docking algorithm as before, the state should already be saved. So, let's say before you had a folder called jd_tutorial/ in your home folder where you were performing your docking from. Whereas before you might have been typing in jd_tutorial/:

dock.py -ir 1dfj_0_sim_map -il 1dfj_1_sim_map -np 12
Now, from the same folder, can you instead type:
mpirun -np 12 /folder/to/POW/POW_v2/parse.py input_ensemble

where /folder/to/POW/ is the path to where the updated POW_v2 has been installed (e.g. /data/home/).

This will skip the optimisation steps you've already performed before entirely, and go straight to the postprocessing (i.e. producing your models and clustering) and should only take a matter of minutes.
Note this is a fix for what you've currently achieved, in future everything should work from just the dock.py command, though you're always welcome to do the postprocessing step independently if you like.

Hope this helps. Let me know how it goes
Cheers,
Lucas

―

**Comment by dclw29** [comment]
Hi,
Thank you for sending me the zip file, it did indeed help me identify the issue.

Looks like there was a typo in `/methods/geometry.pyx` which should have been corrected ages ago (I corrected on my system but failed to update on the github repo).

If you pull from github again, or alternatively copy, paste and replace just the geometry.pyx script in the methods folder it should work.

Don't forget you will also need to run:
`python setup.py install`
From the main JabberDock folder.

Thank you for bearing with, hopefully it should be fine this time. Let me know how it goes though.
Cheers,
Lucas

**Comment by caiyingchun** [comment]
Hi,

It works. Thanks.

When I try another PDB file, in build map step, another new issue raise as below:

> Building the voxel map...
WARNING: found residue with name HIS, checking to see what protonation state it is in and reassigning to HIP, HIE or HID.
You should check HIS in your pdb file is right to be sure!
Conversion Complete
> Grid built, creating a dipole map
Traceback (most recent call last):
  File "/home/applic/JabberDock/auto_scripts/build_map.py", line 126, in <module>
    dipoles  = M.get_dipole_map(orig = orig, pqr = M_pqr, time_start = time_start, time_end = time_end, write_dipole_map = dip_map, vox_in_window = vox, resolution = width, fname = outname + ".tcl")
  File "/home/applic/miniconda2/lib/python2.7/site-packages/biobox/classes/molecule.py", line 1396, in get_dipole_map
    dipole_map = e_density.c_get_dipole_map(crd = crd, orig = orig, charges = charges, time_start = time_start, time_end = time_end,resolution = resolution, vox_in_window = vox_in_window, write_dipole_map = write_dipole_map, fname = fname)
  File "e_density.pyx", line 10, in e_density.c_get_dipole_map
  File "e_density.pyx", line 50, in e_density.c_get_dipole_map
IndexError: index 1 is out of bounds for axis 0 with size 1

I attached the pdb file I used, so you can try it. Thanks very much.
________________________________
发件人: dclw29 <notifications@github.com>
发送时间: 2020年5月25日 10:16
收件人: degiacom/JabberDock <JabberDock@noreply.github.com>
抄送: Yingchun Cai <cai_yingchun@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [degiacom/JabberDock] NameErrorNameError: name 'post' is not defined (#2)


Hi,
Thank you for sending me the zip file, it did indeed help me identify the issue.

Looks like there was a typo in /methods/geometry.pyx which should have been corrected ages ago (I corrected on my system but failed to update on the github repo).

If you pull from github again, or alternatively copy, paste and replace just the geometry.pyx script in the methods folder it should work.

Don't forget you will also need to run:
python setup.py install
From the main JabberDock folder.

Thank you for bearing with, hopefully it should be fine this time. Let me know how it goes though.
Cheers,
Lucas

―
