### ISSUE TITLE
Buid map error with tutorial files

### ISSUE THREAD

**Issue by gpmejias** [degiacom/JabberDock#5]
Hi!
I have installed the JabberDock software and I am trying to run the tutorial to get used to the program. 
Unfortunately, I am not able to generate the STID map with build_map.py after the MD simulation. 
I get this error:

```
(jabberdock) [gperez@nodo09 tutorial-2]$ build_map.py -i 1dfj_0_sim.pdb -ff_dat /home/gperez/data/opt/biobox/classes/amber03.dat
/home/gperez/data/opt/JabberDock/auto_scripts/build_map.py -i 1dfj_0_sim.pdb -ff_dat /home/gperez/data/opt/biobox/classes/amber03.dat
> Building the voxel map...
Traceback (most recent call last):
  File "/home/gperez/data/opt/JabberDock/auto_scripts/build_map.py", line 97, in <module>
    M_pqr = M.pdb2pqr(ff=ff)
  File "/home/gperez/data/opt/JabberDock/biobox/classes/molecule.py", line 1087, in pdb2pqr
    intervals = self.guess_chain_split()[1]
  File "/home/gperez/data/opt/JabberDock/biobox/classes/molecule.py", line 833, in guess_chain_split
    raise Exception("mismatch in N and C count")
Exception: mismatch in N and C count
```

This is the log file of gmx_run:
```
/home/gperez/data/opt/JabberDock/auto_scripts/gmx_run.py -i 1dfj_0.pdb -ff amber03 -gpu 0
> Initiating MD setup...
> Beginning energy minimisation
> Minimisation complete. Initialising equilibriation...
> Equilibiration complete. Initialising production...
> Gromacs run successfully completed, beginning parsing the data
> Converting trajectory to multipdb
> Gromacs run completed successfully. Check 1dfj_0_sim.pdb for the final result and input to the next stage
gmx_run.log (END)
```

**Comment by dclw29** [comment]
Hi gpmejias,

Sorry for the delayed response. Would you mind letting me know what version of biobox you're using? Is it the one shipped with JabberDock or did you pip / conda install biobox on the command line?
Thank you, we should be able to resolve this soon.

Thanks,
Lucas

**Comment by wangkaiyours** [comment]
> Hi gpmejias,
> 
> Sorry for the delayed response. Would you mind letting me know what version of biobox you're using? Is it the one shipped with JabberDock or did you pip / conda install biobox on the command line? Thank you, we should be able to resolve this soon.
> 
> Thanks, Lucas

Hi Lucas，

I have the same problem as gpmejias.
For the JabberDock program, I installed it step by step according to the run_jabberdock.sh in the JabberDock folder, and when I run the command in this example, the following error occurs.

I ran the following command:
conda activate jabberdock
mkdir jd_tutorial
cd jd_tutorial
cp ~/JabberDock/tutorial/*pdb ./
 /opt/software/anaconda3/envs/jabberdock/bin/python2.7 /root/JabberDock/auto_scripts/jabberdock.py -ir 1dfj_0.pdb -il 1dfj_1.pdb -np 12 -ntomp 4

I get this error:
vmd > > Gromacs run completed successfully. Check 1dfj_0_sim.pdb for the final result and input to the next stage
> Converting MD output to STID maps...
/root/JabberDock/auto_scripts/build_map.py -i 1dfj_1_sim.pdb -ff /root/biobox/classes/amber03.dat
> Building the voxel map...
WARNING: found residue with name HIS, checking to see what protonation state it is in and reassigning to HIP, HIE
You should check HIS in your pdb file is right to be sure!
Conversion Complete
> Grid built, creating a dipole map
> Dipole map written, building the STID map...
> Creating a single PDB structure centered in your maps
> STID map building complete. Check 1dfj_1_sim_map.pdb and 1dfj_1_sim_map.dx for output and input for docking
/root/JabberDock/auto_scripts/build_map.py -i 1dfj_0_sim.pdb -ff /root/biobox/classes/amber03.dat
> Building the voxel map...
Traceback (most recent call last):
  File "/root/JabberDock/auto_scripts/build_map.py", line 88, in <module>
    M_pqr = M.pdb2pqr(ff=ff)
  File "/root/JabberDock/biobox/classes/molecule.py", line 1087, in pdb2pqr
    intervals = self.guess_chain_split()[1]
  File "/root/JabberDock/biobox/classes/molecule.py", line 833, in guess_chain_split
    raise Exception("mismatch in N and C count")
Exception: mismatch in N and C count
> Maps complete, beginning docking procedure...
/root/JabberDock/auto_scripts/dock.py -ir 1dfj_1_sim_map -il 1dfj_0_sim_map -np 40
> Setting up input script and defining boundary conditions...
> Beginning POW run

>         Parallel Optimization Workbench (POW)          <
> (c) 2012-14 Laboratory for Biomolecular Modeling, EPFL <

> PREPROCESSING

>> loading module generate_ensemble...
~~~~ALL IMPORTS COMPLETE~~~~
ERROR: ligand building block pdb file 1dfj_0_sim_map.pdb not found
~~~~ALL IMPORTS COMPLETE~~~~
ERROR: ligand building block pdb file 1dfj_0_sim_map.pdb not found
~~~~ALL IMPORTS COMPLETE~~~~
ERROR: ligand building block pdb file 1dfj_0_sim_map.pdb not found


Thanks,
Xiaotaiyang

**Comment by Zaotaiyang** [comment]
> Hi! I have installed the JabberDock software and I am trying to run the tutorial to get used to the program. Unfortunately, I am not able to generate the STID map with build_map.py after the MD simulation. I get this error:
> 
> ```
> (jabberdock) [gperez@nodo09 tutorial-2]$ build_map.py -i 1dfj_0_sim.pdb -ff_dat /home/gperez/data/opt/biobox/classes/amber03.dat
> /home/gperez/data/opt/JabberDock/auto_scripts/build_map.py -i 1dfj_0_sim.pdb -ff_dat /home/gperez/data/opt/biobox/classes/amber03.dat
> > Building the voxel map...
> Traceback (most recent call last):
>   File "/home/gperez/data/opt/JabberDock/auto_scripts/build_map.py", line 97, in <module>
>     M_pqr = M.pdb2pqr(ff=ff)
>   File "/home/gperez/data/opt/JabberDock/biobox/classes/molecule.py", line 1087, in pdb2pqr
>     intervals = self.guess_chain_split()[1]
>   File "/home/gperez/data/opt/JabberDock/biobox/classes/molecule.py", line 833, in guess_chain_split
>     raise Exception("mismatch in N and C count")
> Exception: mismatch in N and C count
> ```
> 
> This is the log file of gmx_run:
> 
> ```
> /home/gperez/data/opt/JabberDock/auto_scripts/gmx_run.py -i 1dfj_0.pdb -ff amber03 -gpu 0
> > Initiating MD setup...
> > Beginning energy minimisation
> > Minimisation complete. Initialising equilibriation...
> > Equilibiration complete. Initialising production...
> > Gromacs run successfully completed, beginning parsing the data
> > Converting trajectory to multipdb
> > Gromacs run completed successfully. Check 1dfj_0_sim.pdb for the final result and input to the next stage
> gmx_run.log (END)
> ```

Hi!

I have encountered the same error as you. Have you solved it?  How is it solved ?

Thanks,
Dashboard
